### PR TITLE
Added a README

### PR DESCRIPTION
**Pull request by BachToTheFuture**
There were some ... "complications" with the screenshot. Haiku wouldn't let me take a screenshot of just the app, so I ended up having to manually crop out the window :(

Also, the app obviously doesn't work, as stated by issue #2. Should I say that in the README?

### CODE REVIEW

**Comment by scottmc** [comment]
Yes.  Please make it clear that it isn't useful for anything in its current state.

**Comment by ddacw** [comment]
I made the PR at dawn so maybe I forgot to save Readme.md...
The screenshot is quite good. For app like this I use Photoshop to get rid of redundancies. Or you can use WonderBrush in Haiku. 

edit: no wonder why

untitled

also, my screenshot
screenshot 139

**Comment by scottmc** [comment]
Read comments from the original author on issue #2 and then update the readme to say that it is unfinished and non-working at this time.

**Comment by BachToTheFuture** [comment]
@scottmc I updated the README 😃 
... and added a list of dependencies, so just in case some if some of these don't exist in Haiku yet, we could port them to HaikuPorts.

**Pull request merged**
